---
- name: Install Google Chrome on Windows
  hosts: windows
  tasks:
    - name: Ensure C:\Temp directory exists
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - name: Download Google Chrome installer
      ansible.windows.win_get_url:
        url: https://dl.google.com/chrome/install/latest/chrome_installer.exe
        dest: C:\Temp\chrome_installer.exe

    - name: Install Google Chrome
      ansible.windows.win_command:
        cmd: C:\Temp\chrome_installer.exe /silent /install
        creates: C:\Program Files\Google\Chrome\Application\chrome.exe
