---
- name: Install VLC on Windows
  hosts: windows
  tasks:
    - name: Ensure C:\Temp directory exists
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - name: Download VLC installer
      ansible.windows.win_get_url:
        url: https://get.videolan.org/vlc/3.0.21/win64/vlc-3.0.21-win64.exe
        dest: C:\Temp\vlc_installer.exe

    - name: Install VLC
      ansible.windows.win_command:
        cmd: C:\Temp\vlc_installer.exe /S
        creates: C:\Program Files\VideoLAN\VLC\vlc.exe
